[versions]
coroutines = "1.8.0"
kotest = "5.8.0"
kotlin = "1.9.22"
knit = "0.5.0"
arrow = "1.2.3"
ksp = "1.9.23-1.0.19"
suspendapp = "0.4.0"
kotlinKafka = "0.3.1"
cache4k = "0.13.0"

[libraries]
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test" }
arrow-core-lib = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
arrow-core-highArity = { module = "io.arrow-kt:arrow-core-high-arity", version.ref = "arrow" }
arrow-core-serialization = { module = "io.arrow-kt:arrow-core-serialization", version.ref = "arrow" }
arrow-fx-coroutines = { module = "io.arrow-kt:arrow-fx-coroutines", version.ref = "arrow" }
arrow-autoclose = { module = "io.arrow-kt:arrow-autoclose", version.ref = "arrow" }
arrow-resilience = { module = "io.arrow-kt:arrow-resilience", version.ref = "arrow" }
arrow-atomic = { module = "io.arrow-kt:arrow-atomic", version.ref = "arrow" }
arrow-fx-stm = { module = "io.arrow-kt:arrow-fx-stm", version.ref = "arrow" }
arrow-optics-lib = { module = "io.arrow-kt:arrow-optics", version.ref = "arrow" }
arrow-optics-plugin = { module = "io.arrow-kt:arrow-optics-ksp-plugin", version.ref = "arrow" }
arrow-optics-reflect = { module = "io.arrow-kt:arrow-optics-reflect", version.ref = "arrow" }
arrow-optics-compose = { module = "io.arrow-kt:arrow-optics-compose", version.ref = "arrow" }
arrow-collectors = { module = "io.arrow-kt:arrow-collectors", version.ref = "arrow" }
arrow-eval = { module = "io.arrow-kt:arrow-eval", version.ref = "arrow" }
arrow-cache4k = { module = "io.arrow-kt:arrow-cache4k", version.ref = "arrow" }
kotlinx-knit = { module = "org.jetbrains.kotlinx:kotlinx-knit", version.ref = "knit" }
kotlinx-knit-test = { module = "org.jetbrains.kotlinx:kotlinx-knit-test", version.ref = "knit" }
suspendapp = { module = "io.arrow-kt:suspendapp", version.ref = "suspendapp" }
kafka-kotlin = { module = "io.github.nomisrev:kotlin-kafka", version.ref = "kotlinKafka" }
cache4k = { module = "io.github.reactivecircus.cache4k:cache4k", version.ref = "cache4k" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinx-knit = { id = "org.jetbrains.kotlinx.knit", version.ref = "knit" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
